### ISSUE TITLE
How to check honest is honest?

### ISSUE THREAD

**Issue by 0xKira** [david942j/honest#10]
XD

**Comment by cebe** [comment]
https://github.com/david942j/honest#installation

says:

> `git clone https://github.com/david942j/honest`

so with that you get what is on github (the definition of what "honest" means in this situation for other packages checked). You can still verify that:

```
cd honest
git show HEAD |head -1
```

if the commit hash shown there is the same you see on github, the content is identical.

For a deeper meaning of being honest in the sense of "works as described" you need to check the source.

**Comment by 0xKira** [comment]
Just kidding. Thanks @cebe

**Comment by cebe** [comment]
> Just kidding.

well, if you can't tell if you can trust the thing you do verification with, the verification is worthless so "How to check honest is honest?" is a valid question to ask. ;)
